name: Run Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build solution
        run: dotnet build --no-restore
        
      - name: Test .NET
        run: dotnet test --no-build --verbosity normal

  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./camera-frontend
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
          cache: 'npm'
          cache-dependency-path: './camera-frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        env:
          NEXT_LINT_ARGS: "--max-warnings 0"
        
      - name: Test Next.js and React
        run: npm test -- --passWithNoTests

  build:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.401'
      
      - name: Backend Build
        run: |
          dotnet restore
          dotnet build --configuration Release
        
      - name: Frontend Build
        run: |
          npm ci
          npm run build
        working-directory: ./camera-frontend